# This is a basic workflow to help you get started with Actions

name: CI - Build Only

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the 'delivery' branch
on:
  push:
    branches:
      - 'build-only'
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        dotnet-version: [ '6.0.x', '7.0.x','8.0.x' ]
      # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
          include-prerelease: true      
      # Runs the specified script
      #echo pwd
      - name: Display dotnet version
        run: dotnet --version
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
   